### ISSUE TITLE
Only one device is visible under the user account for multiple devices

### ISSUE THREAD

**Issue by rforgo** [pve84/eldom#21]
Only one device is visible under the user account for multiple devices.

## Version of the custom_component

0.0.1

## Configuration

Please list the files you need to troubleshoot

## Describe the bug

Obly one device and two entity available 

## Debug log
-------------------------------------------------------------------
eldom
Version: 0.0.1
This is a custom integration!
If you have any issues with this you need to open an issue here:
https://github.com/pve84/eldom/issues
-------------------------------------------------------------------

2021-11-17 12:41:56 DEBUG (MainThread) [custom_components.eldom] Finished fetching eldom data in 2.101 seconds (success: True)

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/hatasmota/discovery.py", line 208, in discovery_message_received
    payload = TasmotaDiscoveryMsg(json.loads(_payload))
  File "/usr/local/lib/python3.9/site-packages/hatasmota/discovery.py", line 158, in __init__
    config = TASMOTA_DISCOVERY_SCHEMA(config)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: required key not provided @ data['so']['82']

2021-11-17 12:42:26 DEBUG (MainThread) [custom_components.eldom] Finished fetching eldom data in 0.820 seconds (success: True)

**Comment by pve84** [comment]
I currently have only one Eldom device and will probably not buy more of them since I don't think they are very good products. 
Maybe if you can post the responses of the calls to the eldom api (anonymized)than I can try to fix it.

- https://iot.myeldom.com/api/device-list?page=1&size=10
- https://iot.myeldom.com/direct-req

**Comment by rforgo** [comment]
Thank you for the support. After authentication, I try to get a list of devices. However, it was not possible to figure out where the value of ionic-idd is? Unfortunately, I am not a professional in Python programming. If I get an invalid IDD error message for "0" in api.py.

**Comment by rforgo** [comment]
I would have a suggestion, in line 14 and 38 of the climate.py module, the PRECISION_WHOLE constant should be changed to PRECISION_HALVES to match the possible setting values.

**Comment by rforgo** [comment]
Response to the first link:
[
    {
        "uuid": "C501202C*******",
        "model": "HTRCNV",
        "fmodel": "RH30NW",
        "name": "P*****",
        "pairTok": "3inxstzQ*****",
        "ssid": "ELD-RH30NW-C5012*****",
        "pass": "*******",
        "isPaired": true
    },
    {
        "uuid": "AC01203********",
        "model": "HTRCNV",
        "fmodel": "RH30NW",
        "name": "G****",
        "pairTok": "Hm***********",
        "ssid": "ELD-RH30NW-AC01********",
        "pass": "*******",
        "isPaired": true
    },
    {
        "uuid": "19012*********",
        "model": "HTRCNV",
        "fmodel": "RH30NW",
        "name": "S******",
        "pairTok": "ADZOBf*******",
        "ssid": "ELD-RH30NW-190*******",
        "pass": "*******",
        "isPaired": true
    },
    {
        "uuid": "52011*******",
        "model": "HTRCNV",
        "fmodel": "RH30NW",
        "name": "T*****",
        "pairTok": "qdyd34*******",
        "ssid": "ELD-RH30NW-5201*****",
        "pass": "*******",
        "isPaired": true
    }
]

Response to the second link (1st device):
{
    "T": "209",
    "DT": "1637528792",
    "ID": "3inx******u",
    "CID": "*******",
    "CRC": "1EDDF475",
    "Res": "GetStatus",
    "Lock": "0",
    "TSet": "205",
    "Status": "0",
    "TimeZone": "1",
    "Operation": "16",
    "TotPower1": "693",
    "TotPower2": "275"
}

**Comment by leppermesiah** [comment]
Can I join this conversation? I have the same problem. Multiple devices, and only one visible. I was wondering if we can use that many integrations as needed? For example Eldom, Eldom_1, Eldom_2 etc... Then we can change ourselves within the api.py file the id of each device ? Would that be possible somehow? Instead of getting the Device ID from the API website, we can go to https://iot.myeldom.com/ and get the ID's ourselves and put them in the api.py. I hope this explanation make sense. I have 2% experience with Python but I can navigate within the file if needed.

**Comment by pve84** [comment]
So, I will not be working on this project anymore. My Eldom unit refuses to connect to the internet or at least to the api's of Eldom. I think it's blocked by uuid. Maybe because requesting data from the api every 5 sec is too much. I'll leave this code available for anyone that wants to fork it.
