### ISSUE TITLE
UI integration cant show it.

### ISSUE THREAD

**Issue by zsgodor** [pve84/eldom#63]
Hi,
I install this integration, your instruction, but the Configuration -- Integration, i cant see this UI.
Can you help me whats wrong? 
![Képernyőfotó 2022-02-08 - 20 25 21](https://user-images.githubusercontent.com/64435192/153061126-f293044d-906c-45bb-bbfd-de408132b2e9.png)

My system is.:
## System Health

version | core-2022.2.3
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 4.19.0-8-amd64
arch | x86_64
timezone | Europe/Budapest

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.21.0
Stage | running
Available Repositories | 1044
Downloaded Repositories | 18

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 41

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 19.03.11
disk_total | 113.1 GB
disk_used | 40.1 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | TasmoAdmin (0.16.0), Mosquitto broker (6.0.1), SQLite Web (2.2.2), Simple Scheduler (0.35), ESPHome (2022.1.2), Portainer (1.1.0), File editor (5.3.3)

</details>

<details><summary>Lovelace</summary>

dashboards | 4
-- | --
resources | 7
views | 14
mode | storage

</details>

**Comment by pve84** [comment]
This repository is no longer maintained. I no lnoer own an heater bij eldom. It's here so someone can fork it if they want to.
